CoinsManagerWebUI/Models/Api/Coin.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace CoinsManagerWebUI.Models
{
    public partial class Coin
    {
        public int Id { get; set; }
        public string Nominal { get; set; }
        public string Currency { get; set; }
        public string Year { get; set; }
        public int Type { get; set; }
        public string CommemorativeName { get; set; }
        public int Period { get; set; }
        public string PictPreviewPath { get; set; }

        public virtual Period PeriodNavigation { get; set; }
        public virtual CoinType TypeNavigation { get; set; }
    }
}

CoinsManagerWebUI/Models/Api/CoinType.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace CoinsManagerWebUI.Models
{
    public partial class CoinType
    {
        public CoinType()
        {
            Coins = new HashSet<Coin>();
        }

        public int Id { get; set; }
        public string Type { get; set; }

        public virtual ICollection<Coin> Coins { get; set; }
    }
}

CoinsManagerWebUI/Controllers/CoinCatalogController.cs
using CoinsManagerWebUI.Models.View;
using CoinsManagerWebUI.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace CoinsManagerWebUI.Controllers
{
    public class CoinCatalogController : Controller
    {
        private readonly ICoinCatalogService _coinCatalogService;
        private CoinListModel _viewModel = new CoinListModel();
        private readonly ILogger<CoinCatalogController> _logger;

        public CoinCatalogController(ICoinCatalogService coinCatalogService, ILogger<CoinCatalogController> logger)
        {
            _coinCatalogService = coinCatalogService;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            _logger.LogInformation("Home page loading started");
            ViewBag.Title = "Coins";

            var continents = await _coinCatalogService.GetAllContinents();

            foreach (var continent in continents)
            {
                _viewModel.Continents.Add(new SelectListItem() { Value = continent.Id.ToString(), Text = continent.Continent1 });
            }

            ViewData["Continent"] = _viewModel.Continents;
            return View(_viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SelectCountry(CoinListModel model)
        {
            var selectedContinent = model.ContinentId;
            var countries = await _coinCatalogService.GetCountriesByContinentId(Convert.ToInt32(selectedContinent));
            foreach (var country in countries)
            {
                _viewModel.Countries.Add(new SelectListItem() { Value = country.Id.ToString(), Text = country.Country1 });
            }
            return View(_viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Coin(int countryId)
        {
            var country = await _coinCatalogService.GetCountryById(countryId);
            _viewModel.Country = country;
            var continent = await _coinCatalogService.GetContinentById(country.Continent);
            _viewModel.Continent = continent;
            var periods = await _coinCatalogService.GetPeriodsByCountryId(countryId);
            _viewModel.Periods = periods.ToList();
            foreach (var period in periods)
            {
                var coins = await _coinCatalogService.GetCoinsByPeriod(Convert.ToInt32(period.Id));
                _viewModel.Coins.AddRange(coins);
            }
            return View("Coins", _viewModel);
        }
    }
}

CoinsManagerWebUI/Views/CoinCatalog/Coins.cshtml
@model CoinsManagerWebUI.Models.View.CoinListModel
@{
    /**/

    ViewBag.Title = "Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h1>@Model.Continent.Continent1</h1>
<h2>@Model.Country.Country1</h2>
@foreach (var period in Model.Coins.Select(x => x.Period).Distinct())
    {
        <div class="card-header" style="max-width: 905px">
            <h3>@Model.Periods.FirstOrDefault(x => x.Id == period).Period1</h3>
        </div>
        <br />
        <table>
            @for (int i = 0; i < Model.Coins.Where(x => x.Period == period).ToList().Count; i += 3)
            {
                <tr>
                    <td>
                        <div class="my-container">
                            @{ string imageCol1Location = "https://coinsdatastorage.blob.core.windows.net/thumbnails" + Model.Coins.Where(x => x.Period == period).ToList()[i].PictPreviewPath.Replace(@"\","/"); }
                            <a href="@imageCol1Location"><img src="@Url.Content(@imageCol1Location)" class="table table-hover" style="max-width: 300px"></a>
                            <div class="my-text-block">
                                @Model.Coins.Where(x => x.Period == period).ToList()[i].Nominal @Model.Coins.Where(x => x.Period == period).ToList()[i].Currency @Model.Coins.Where(x => x.Period == period).ToList()[i].Year @(" #")@(Model.Coins.Where(x => x.Period == period).ToList()[i].Id)
                                
                            </div>
                        </div>
                    </td>

                    @if (Model.Coins.Where(x => x.Period == period).ToList().Count > i + 1)
                    {
                        <td>
                            <div class="my-container">
                                @{ string imageCol2Location = "https://coinsdatastorage.blob.core.windows.net/thumbnails" + Model.Coins.Where(x => x.Period == period).ToList()[i + 1].PictPreviewPath.Replace(@"\","/"); }
                                <a href="@imageCol2Location"><img src="@Url.Content(@imageCol2Location)" class="table table-hover" style="max-width: 300px"></a>
                                <div class="my-text-block ">
                                    @Model.Coins.Where(x => x.Period == period).ToList()[i + 1].Nominal @Model.Coins.Where(x => x.Period == period).ToList()[i + 1].Currency @Model.Coins.Where(x => x.Period == period).ToList()[i + 1].Year  @(" #")@Model.Coins.Where(x => x.Period == period).ToList()[i + 1].Id
                                    
                                </div>
                            </div>
                        </td>
                    }

                    @if (Model.Coins.Where(x => x.Period == period).ToList().Count > i + 2)
                    {
                        <td>
                            <div class="my-container">
                                @{ string imageCol3Location = "https://coinsdatastorage.blob.core.windows.net/thumbnails" + Model.Coins.Where(x => x.Period == period).ToList()[i + 2].PictPreviewPath.Replace(@"\","/"); }
                                <a href="@imageCol3Location"><img src="@Url.Content(@imageCol3Location)" class="table table-hover" style="max-width: 300px"></a>
                                <div class="my-text-block">
                                    @Model.Coins.Where(x => x.Period == period).ToList()[i + 2].Nominal @Model.Coins.Where(x => x.Period == period).ToList()[i + 2].Currency @Model.Coins.Where(x => x.Period == period).ToList()[i + 2].Year @(" #")@Model.Coins.Where(x => x.Period == period).ToList()[i + 2].Id
                                    
                                </div>
                            </div>
                        </td>
                    }
                </tr>
            }
        </table>
    }

    <input type="button"
         value="Previous Country"
         onclick="location.href='@Url.Action("Coin", "CoinCatalog", new {countryId = Model.Country.Id - 1})'" />
    <input type="button"
         value="Next Country"
         onclick="location.href='@Url.Action("Coin", "CoinCatalog", new {countryId = Model.Country.Id + 1})'" />
@*    <input type="button"
         value="Add coin"
         onclick="location.href='@Url.Action("CreateCoin", "CoinCatalog")'" />*@

CoinsManagerWebUI/Views/CoinCatalog/Index.cshtml
@model CoinsManagerWebUI.Models.View.CoinListModel
@{
    /**/

    ViewBag.Title = "Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="width: 100%; display: table;">
    <div style="display: table-row">
        <div style="display: table-cell; vertical-align: top; text-align: left; padding-right: 20px">
            @using (Html.BeginForm("SelectCountry", "CoinCatalog", FormMethod.Post))
            {
                @Html.DropDownListFor(m => m.ContinentId, Model.Continents, "--Select Continent--", new { @class = "form-control" });
                
                <input type="submit" value="Submit">
            }            
        </div>
        <div style="display: table-cell;">
        </div>
    </div>
</div>
<br />

CoinsManagerWebUI/Views/CoinCatalog/SelectCountry.cshtml
@model CoinsManagerWebUI.Models.View.CoinListModel
@{
    /**/

    ViewBag.Title = "Collection";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div style="width: 100%; display: table;">
    <div style="display: table-row">
        <div style="display: table-cell; vertical-align: top; text-align: left; padding-right: 20px">
            @using (Html.BeginForm("Coin", "CoinCatalog", FormMethod.Get))
            {
                @Html.DropDownListFor(m => m.CountryId, Model.Countries, "--Select Country--", new { @class = "form-control" });
                
                <input type="submit" value="Submit">
            }            
        </div>
        <div style="display: table-cell;">
        </div>
    </div>
</div>
<br />